sphinx_doc/migration/Eloquent.rst
Via https://github.com/ros-planning/navigation2/pull/1650/
=> Adding map server migration guide

Makefile
Fixing publisher error that CI and local testing couldn't have caught
=> removing reference clones messing up with new dir

substitutions.txt
Fixes #5
I also need an actual content change to test #7, it turns out.
=> Fix TB3 manual link.

_themes/otc_tcs_sphinx_theme/layout.html
Signed-off-by: Shrijit Singh <shrijitsingh99@gmail.com>
Resolves #4
=> Add edit on GitHub button

migration/Eloquent.rst, plugins/index.rst
Signed-off-by: Sarthak Mittal <sarthakmittal2608@gmail.com>
As per https://github.com/ros-planning/navigation2/pull/1705
=> Add distance traveled and time expired condition nodes

configuration/configuring-the-bt.rst, configuration/index.rst, configuration/params/tunable-params.rst
This is a proposal for the parameters representation.
It probably makes more sense to have the parameters for each node in a separate page to avoid having them all crammed in single page.
Please let me know what you think.
=> Parameters descriptions

configuration/index.rst, configuration/packages/configuring-navfn.rst, configuration/packages/configuring-planner-server.rst
=> adding navfn and planner server param descriptions

configuration/index.rst, configuration/packages/configuring-map-server.rst
@Marwan99, you know the drill #21
=> add map server docs

configuration/index.rst, configuration/packages/configuring-map-server.rst, configuration/packages/configuring-recovery-server.rst
=> adding recoveries server param

configuration/index.rst, configuration/packages/configuring-amcl.rst
=> adding AMCL params to config guide

configuration/packages/configuring-controller-server.rst, configuration/packages/configuring-costmaps.rst, configuration/packages/configuring-dwb-controller.rst, configuration/packages/configuring-navfn.rst, configuration/packages/configuring-planner-server.rst, configuration/packages/configuring-recovery-server.rst, configuration/packages/dwb-params/iterator.rst, migration/Eloquent.rst
Signed-off-by: Sarthak Mittal <sarthakmittal2608@gmail.com>
As per: https://github.com/ros-planning/navigation2/issues/1791 and https://github.com/ros-planning/navigation2/pull/1808
=> Add updated plugin map parameter parsing mechanics

configuration/packages/configuring-controller-server.rst, configuration/packages/configuring-dwb-controller.rst, configuration/packages/nav2_controller-plugins/simple_goal_checker.rst, configuration/packages/nav2_controller-plugins/simple_progress_checker.rst, configuration/packages/nav2_controller-plugins/stopped_goal_checker.rst, migration/Eloquent.rst
Doc changes for ros-planning/navigation2#1857
Updates to migration and configuration guides to
reflect the changes in plugins
Signed-off-by: Siddarth Gore <siddarth.gore@gmail.com>
=> Move goal/progress plugins from DWB to nav2_controller

configuration/packages/configuring-amcl.rst
Goes along with the PR here https://github.com/ros-planning/navigation2/pull/1870
=> Added topic param to amcl configuration guide

plugins/index.rst
Hi!!
I forgot in #40 adding the new BT plugins to the Navigation plugins page.
Signed-off-by: Francisco Martin Rico <fmrico@gmail.com>
=> Documenting Navigation plugins

build_instructions/index.rst
Updated `ros2_dependencies.repos` to `underlay.repos`.
=> Updated dependencies file name

tutorials/docs/writing_new_recovery_plugin.rst, tutorials/index.rst
Corresponding to https://github.com/ros-planning/navigation2_tutorials/pull/6
=> adding recovery tutorial

configuration/packages/configuring-dwb-controller.rst
Fixes #80 
Signed-off-by: Siddarth Gore <siddarth.gore@gmail.com>
=> Add progress/goal checker plugins to dwb docs

configuration/packages/bt-plugins/conditions/IsBatteryLow.rst, configuration/packages/configuring-bt-xml.rst, migration/Eloquent.rst, plugins/index.rst
As per https://github.com/ros-planning/navigation2/pull/1974
=> Add IsBatteryLow BT Condition node info

configuration/packages/configuring-map-server.rst, tutorials/docs/navigation2_with_keepout_filter.rst
This is continue items for PR #85
=> Update YouTube video and make small improvements for keepouts

configuration/packages/configuring-waypoint-follower.rst, configuration/packages/nav2_waypoint_follower-plugins/input_at_waypoint.rst, migration/Foxy.rst, plugins/index.rst
Analog for https://github.com/ros-planning/navigation2/pull/2049#pullrequestreview-517284650
=> adding input at waypoint plugin

configuration/packages/configuring-smac-planner.rst, migration/Foxy.rst, plugins/index.rst
Signed-off-by: Tony Najjar <tony.najjar.1997@gmail.com>
Commit message says it all. This pull request is a complement to [this pull request](https://github.com/ros-planning/navigation2/pull/2093) for this [issue](https://github.com/ros-planning/navigation2/issues/2092)
=> Added nav2_ prefix to smac_planner documentation

configuration/packages/configuring-lifecycle.rst, configuration/packages/configuring-map-server.rst, configuration/packages/configuring-smac-planner.rst, migration/Foxy.rst
synch with https://github.com/ros-planning/navigation2/pull/2106
=> Standardize time units per REP-103

migration/Foxy.rst
- Pending successsful merge of https://github.com/ros-planning/navigation2/pull/1855/files
=> Updated migration guide due to #1855

configuration/packages/dwb-params/controller.rst
https://github.com/ros-planning/navigation2/pull/2188
=> dwb's shorten_transformed_plan docs

migration/Foxy.rst
https://github.com/ros-planning/navigation2/pull/2181
=> NavFn Planner Reconfigurable Parameters doc

configuration/packages/bt-plugins/actions/ClearCostmapAroundRobot.rst, configuration/packages/bt-plugins/actions/ClearCostmapExceptRegion.rst, configuration/packages/configuring-bt-xml.rst, migration/Foxy.rst, plugins/index.rst
See https://github.com/ros-planning/navigation2/pull/2204
=> Docs for PR #2204

configuration/packages/bt-plugins/actions/ComputePathToPose.rst, migration/Foxy.rst
See https://github.com/ros-planning/navigation2/pull/2179/files
=> Added migration and doc update for #2179

configuration/packages/configuring-bt-navigator.rst
https://github.com/ros-planning/navigation2/issues/2234
=> goal blackboard id param

configuration/packages/configuring-bt-navigator.rst, configuration/packages/configuring-bt-xml.rst, migration/Foxy.rst, plugins/index.rst
https://github.com/ros-planning/navigation2/pull/2236
=> adding single trigger BT node configurations

configuration/packages/configuring-regulated-pp.rst, migration/Foxy.rst
https://github.com/ros-planning/navigation2/pull/2247
=> removing RPP parameter removed and updating migration guide about goal checker and controller changes

configuration/packages/bt-plugins/actions/ControllerSelector.rst, configuration/packages/configuring-bt-xml.rst, migration/Foxy.rst, plugins/index.rst
Associated PR in navigation2 main branch
https://github.com/ros-planning/navigation2/pull/2266
=> controller selector documentation

setup_guides/urdf/setup_urdf.rst
Apply fixes from https://github.com/ros-planning/navigation2_tutorials/pull/27
=> Apply corrections to urdf setup guide for caster wheel radius

setup_guides/urdf/setup_urdf.rst
Linked Issue: []https://github.com/ros-planning/navigation.ros.org/issues/175
=> Removal of the undefined macro

migration/Galactic.rst
Signed-off-by: zhenpeng ge <zhenpeng.ge@qq.com>
update migration docs of Galactic.
=> add migration of <Reduce Nodes and Executors>

migration/Galactic.rst
Signed-off-by: zhenpeng ge <zhenpeng.ge@qq.com>
=> update migration for 'reduce nodes and executors'

migration/Galactic.rst
update galactic.rst about the change in  nav2 PR
https://github.com/ros-planning/navigation2/pull/2473
- deletion of nav2_gazebo_spawner pkg
=> update galactic.rst on nav2_gazebo_spawner deletion

configuration/packages/configuring-bt-navigator.rst, migration/Galactic.rst
https://github.com/ros-planning/navigation2/pull/2696
=> removing live groot monitoring

configuration/packages/smac/configuring-smac-hybrid.rst, configuration/packages/smac/configuring-smac-lattice.rst, migration/Galactic.rst
https://github.com/ros-planning/navigation2/pull/2697
=> adding max length param to smac planner

setup_guides/odom/setup_odom.rst
See https://github.com/ros-planning/navigation2_tutorials/pull/41
=> Fix wheel_separation value in odometry guide

setup_guides/index.rst, setup_guides/lifecycle_composition/setup_lifecycle_composition.rst
Co-authored-by: Josen De Leon jd.deleon@samsung.com
Co-authored-by: Fiona Estoperez f.estoperez@samsung.com
Co-authored-by: Steve Macenski stevenmacenski@gmail.com
=> Add Lifecycle and Composition Tutorial Guide

setup_guides/odom/setup_odom.rst, setup_guides/sensors/setup_sensors.rst
Update Odometry and Sensors Setup Guide to reflect changes in:
- `display.launch.py` ros-planning/navigation2_tutorials#45
- `sam_bot_description.urdf` ros-planning/navigation2_tutorials#46
=> Update Odometry and Sensors Setup Guide

configuration/packages/smac/configuring-smac-hybrid.rst, configuration/packages/smac/configuring-smac-lattice.rst, migration/Galactic.rst
Added notes about smac planner heuristic admissibility fix and retrospective penalty
=> Smac admissible heuristic update

setup_guides/odom/setup_odom.rst
Guide references to old ROS 1 tutorials on tf2 while new ones available and may be more relevant
=> Update links to tf2 broadcaster tutorials

commander_api/index.rst
Consequence of https://github.com/ros-planning/navigation2/pull/2792
=> Add recoveries to simple commander

tutorials/docs/navigation2_with_stvl.rst
Follow up to https://github.com/SteveMacenski/spatio_temporal_voxel_layer/pull/227
=> Remove unused parameter

2021summerOfCode/projects/spinners.rst, behavior_trees/index.rst, configuration/packages/bt-plugins/conditions/IsPathValid.rst, configuration/packages/nav2_waypoint_follower-plugins/photo_at_waypoint.rst, configuration/packages/nav2_waypoint_follower-plugins/wait_at_waypoint.rst, migration/Foxy.rst, migration/Galactic.rst, setup_guides/odom/setup_odom.rst, tutorials/docs/get_backtrace.rst
Cleaning up annoying warnings after you build, but there is still more warnings which needs time and I will address them later in a separate PR.
=> removing the annoying warnings after build

configuration/packages/bt-plugins/actions/CancelBackUp.rst, configuration/packages/bt-plugins/actions/CancelSpin.rst, configuration/packages/bt-plugins/actions/CancelWait.rst, configuration/packages/configuring-bt-xml.rst, migration/Galactic.rst, plugins/index.rst
related to [PR 2856](https://github.com/ros-planning/navigation2/pull/2856)
=> adding docu for cancel recoveries

migration/Galactic.rst
address changes introduced by https://github.com/ros-planning/navigation2/pull/2865
=> Remove 3D: Update migration guide

configuration/packages/configuring-amcl.rst
=> Added first_map_only parameter in docs

configuration/packages/configuring-controller-server.rst, configuration/packages/configuring-dwb-controller.rst, configuration/packages/configuring-regulated-pp.rst, configuration/packages/configuring-rotation-shim-controller.rst, tutorials/docs/using_shim_controller.rst
Per https://github.com/ros-planning/navigation2/issues/2895
=> updating goal_checker_plugin to goal_checker_plugins

configuration/packages/bt-plugins/actions/NavigateThroughPoses.rst, configuration/packages/bt-plugins/actions/NavigateToPose.rst
Docs for https://github.com/ros-planning/navigation2/pull/2952
=> Added docs for new inputs

configuration/packages/configuring-amcl.rst, plugin_tutorials/docs/writing_new_behavior_plugin.rst, plugin_tutorials/docs/writing_new_costmap2d_plugin.rst, plugin_tutorials/docs/writing_new_nav2planner_plugin.rst, tutorials/docs/navigation2_with_stvl.rst
Fix points
1. change "Recovery" to "Behavior"
2. delete  Eloquent and earlier info (because EOL version)
=> change plugin tutorials for humble

migration/Humble.rst
Migration docs for https://github.com/ros-planning/navigation2/pull/3131
=> use_sim_time from launch files docs

configuration/packages/configuring-collision-monitor.rst, tutorials/docs/using_collision_monitor.rst
Documentation updates for adding range sensors to Collision Monitor (related to https://github.com/ros-planning/navigation2/pull/3099)
=> Add range sensors support to Collision Monitor

commander_api/index.rst
include documentation for python cost api for the simple commander
=> Python cost api documentation

migration/Humble.rst
Documentation for https://github.com/ros-planning/navigation2/pull/3146
=> migration guide

migration/Humble.rst
Concerned with https://github.com/ros-planning/navigation2/pull/3229
=> Add Costmap Filters enabling service to Iron MG

configuration/packages/configuring-lifecycle.rst
I found this error in the docs.
Cheers Moritz
=> fix type of bond_timeout

tutorials/docs/get_backtrace.rst
Found faster debugging steps than the provided documentation.
=> faster debug

configuration/packages/configuring-collision-monitor.rst, tutorials/docs/using_collision_monitor.rst
Documentation updates related to the https://github.com/ros-planning/navigation2/pull/3245
=> Adjust documentation pages for dynamic polygons

tutorials/docs/using_collision_monitor.rst
This is PR to meet the latest review item from PR382: https://github.com/ros-planning/navigation.ros.org/pull/372#discussion_r1025624985
=> Add to tutorial dynamic polygons advertising

migration/Humble.rst
covers https://github.com/ros-planning/navigation2/pull/3165
=> add docu for load, loop save waypoint in RViz panel

configuration/packages/bt-plugins/conditions/AreErrorCodesPresent.rst, configuration/packages/bt-plugins/conditions/WouldAControllerRecoveryHelp.rst, configuration/packages/bt-plugins/conditions/WouldAPlannerRecoveryHelp.rst, configuration/packages/bt-plugins/conditions/WouldASmootherRecoveryHelp.rst, configuration/packages/configuring-bt-xml.rst, migration/Humble.rst, plugins/index.rst, tutorials/docs/adding_smoother.rst
Updated documentation for the new smoother error code bt node
=> added smoother error code bt node 

configuration/packages/configuring-regulated-pp.rst, migration/Humble.rst
https://github.com/ros-planning/navigation2/pull/3414
=> add fixed curvature lookahead parameters

configuration/packages/configuring-mppic.rst
=> Fix reset_period

configuration/packages/configuring-controller-server.rst, configuration/packages/nav2_controller-plugins/pose_progress_checker.rst, migration/Humble.rst, plugins/index.rst
For https://github.com/ros-planning/navigation2/pull/3530
=> Add PoseProgressChecker

configuration/packages/smac/configuring-smac-hybrid.rst, migration/Humble.rst
For https://github.com/ros-planning/navigation2/pull/3577
=> viz_expansions planner parameter documentation

tutorials/docs/get_profile.rst
valgrind is called with the wrong argument in the launch file example. it should be `--tool` instead of `--tools`
=> Update profiling tutorial

migration/Iron.rst, plugin_tutorials/docs/writing_new_behavior_plugin.rst
Documentation updates for https://github.com/ros-planning/navigation2/pull/3704. 
Added to migration guide, updated behavior plugin example.
=> behavior server updates

migration/Galactic.rst
It seems to be unintentionally the same as one link above.
=> Fix Galactic.rst (link to wrong pull request)

configuration/packages/smac/configuring-smac-hybrid.rst, migration/Iron.rst
https://github.com/ros-planning/navigation2/pull/3752
=> adding zig zag docs

migration/Iron.rst
Iron->Jazzy MG update with new `RewrittenYaml` functionalittyl, introduced in https://github.com/ros-planning/navigation2/pull/3785
=> New parameters functionality for RewrittenYaml

migration/Iron.rst
For https://github.com/ros-planning/navigation2/pull/3950
=> PR 3950 doc

commander_api/index.rst
Documentation for https://github.com/ros-planning/navigation2/pull/4022
=> Add DriveOnHeading documentation

configuration/packages/collision_monitor/configuring-collision-detector-node.rst, configuration/packages/collision_monitor/configuring-collision-monitor-node.rst, migration/Iron.rst, tutorials/docs/using_collision_monitor.rst
https://github.com/ros-planning/navigation2/pull/4020
Updating the format of polygon points.
=> Docs for #4020

requirements.txt
Reverts ros-planning/navigation.ros.org#505
=> Revert "Bump jinja2 from 3.0.3 to 3.1.3"

configuration/packages/configuring-mppic.rst
Adding `inflation_layer_name` new parameter for obstacle critic
depends on:
=> Add inflation_layer_name doc for MPPI

setup_guides/odom/setup_odom.rst, setup_guides/urdf/setup_urdf.rst
fix for https://github.com/ros-planning/navigation.ros.org/issues/508
=> [bugfix/508] urdf not passed to joint_state_publisher

configuration/packages/smac/configuring-smac-hybrid.rst, configuration/packages/smac/configuring-smac-lattice.rst
=> Fix analytic_expansion_max_cost default value

tutorials/docs/navigation2_with_gps.rst
[Current link](https://navigation.ros.org/tutorials/docs/navigation2_with_gps.html#setup-gazebo-world) is broken for sure, not sure the new one is the correct one though considering it has a version in it, though it is from the stable branch.
=> update sonoma-raceway link in gps tutorial

tutorials/docs/docker_dev.rst
* Use ROS_DISTRO correctly
* One line per command
=> Make dockerfile more readable

tutorials/docs/navigation2_with_keepout_filter.rst
Update the documentation to use composable nodes with keep out filters.
Related to: https://github.com/ros-planning/navigation2_tutorials/pull/89
=> Update the documentation to use composable nodes with keepout filters

migration/Iron.rst
Adding instructions about upgrading BT.CPP
=> add note about upgraded BT.CPP

tutorials/docs/navigation2_with_gps.rst
- make it easier to install the packages
- update the link to Sonoma Raceway
=> imrpovements to gps tutorial

configuration/packages/configuring-rotation-shim-controller.rst, migration/Iron.rst
* docs for rotate_to_goal_heading parameter
=> Docs for PR4332 (#4289)

configuration/packages/bt-plugins/actions/GetPoseFromPath.rst, configuration/packages/configuring-bt-xml.rst, migration/Jazzy.rst, plugins/index.rst
https://github.com/ros-navigation/navigation2/pull/4518
=> Adding get pose from path BT node 

configuration/packages/configuring-docking-server.rst, migration/Jazzy.rst, roadmap/roadmap.rst, tutorials/docs/using_docking.rst
See https://github.com/ros-navigation/navigation2/pull/4627
=> Adding doc updates for docking

configuration/packages/bt-plugins/conditions/IsStopped.rst, configuration/packages/configuring-bt-navigator.rst, migration/Jazzy.rst, plugins/index.rst
https://github.com/ros-navigation/navigation2/pull/4764
=> Add docs for IsStopped BT node

configuration/packages/collision_monitor/configuring-collision-monitor-node.rst, configuration/packages/configuring-behavior-server.rst, configuration/packages/configuring-controller-server.rst, configuration/packages/configuring-loopback-sim.rst, configuration/packages/configuring-velocity-smoother.rst, migration/Jazzy.rst, tutorials/docs/using_collision_monitor.rst
https://github.com/ros-navigation/nav2_minimal_turtlebot_simulation/pull/16/files
https://github.com/ros-navigation/navigation2/pull/4779
=> Migrating twist to twiststamped in simulations for recommended default bringups

commander_api/index.rst, configuration/packages/bt-plugins/actions/BackUp.rst, configuration/packages/bt-plugins/actions/DriveOnHeading.rst, configuration/packages/bt-plugins/actions/Spin.rst, migration/Jazzy.rst
Docs corresponding to PR https://github.com/ros-navigation/navigation2/pull/4785 (If it is accepted)
=> document the new disable_collision_checks param

configuration/packages/collision_monitor/configuring-collision-detector-node.rst, configuration/packages/collision_monitor/configuring-collision-monitor-node.rst
Supersedes https://github.com/ros-navigation/docs.nav2.org/pull/478
=> Docs for #3885 and #3879

setup_guides/sdf/setup_sdf.rst, setup_guides/urdf/setup_urdf.rst
Fixes https://github.com/ros-navigation/navigation2_tutorials/issues/105.
Corresponding PR to navigation2_tutorials: https://github.com/ros-navigation/navigation2_tutorials/pull/107.
=> Shift inertia to base_footprint

conf.py
* Added dynamic year and author name to copyright.
* Built the website locally to verify changes.
=> Add dynamic copyright year and author.

configuration/packages/configuring-controller-server.rst, configuration/packages/nav2_controller-plugins/position_goal_checker.rst, migration/Jazzy.rst, plugins/index.rst
Added documentation of a new position goal checker plugin. [](https://github.com/ros-navigation/navigation2/pull/5162)
=> added position goal checker

configuration/packages/configuring-mppic.rst
Update the MPPI controller documentation for the enforce_path_inversion parameter.
=> Update doc for MPPI enforce_path_inversion param

setup_guides/odom/setup_odom_gz.rst
Here are some improvements to make the tutorial more beginner-friendly, based on challenges that were faced when it was straightly followed, as described in issue #695.
=> Improvements on Tutorial Setting Up Odometry - Gazebo

configuration/packages/configuring-route-server.rst
https://github.com/nvidia-isaac/SWAGGER/pull/2
=> Adding SWAGGER integration reference to Route

behavior_trees/overview/nav2_specific_nodes.rst, configuration/packages/bt-plugins/controls/PauseResumeController.rst, configuration/packages/bt-plugins/controls/PersistentSequence.rst, configuration/packages/configuring-bt-navigator.rst, configuration/packages/configuring-bt-xml.rst, migration/Kilted.rst, plugins/index.rst
https://github.com/ros-navigation/navigation2/pull/5247
=> Write docs for PauseResumeController and PersistentSequence
