migration/Eloquent.rst
Following https://github.com/ros-planning/navigation2/pull/1677
=> Add particle filter msgs to migration guide

migration/Eloquent.rst, plugins/index.rst
As per https://github.com/ros-planning/navigation2/pull/1699
=> Add DistanceController to plugin list

concepts/index.rst, migration/Eloquent.rst, plugins/index.rst
Signed-off-by: Aitor Miguel Blanco <aitormibl@gmail.com>
* Added new condition node to plugins index (navigation2 #[1712](https://github.com/ros-planning/navigation2/pull/1712)).
* Updated migration guide.
* Added new section for recommended tree structures in concepts, under Behavior Trees.
Other changes:
* Updated links in plugins index.
* Small typos and blank spaces at end of lines.
=> Added documentation for goal preemption on behavior trees

migration/Eloquent.rst, plugins/index.rst
Signed-off-by: Sarthak Mittal <sarthakmittal2608@gmail.com>
As per https://github.com/ros-planning/navigation2/pull/1744
=> Add speed controller to plugin list and migration guide

configuration/packages/configuring-planner-server.rst
It's part of work related to https://github.com/ros-planning/navigation2/pull/1801
=> Added expected_planner_frequency to the Planner Server

configuration/packages/configuring-controller-server.rst, configuration/packages/configuring-costmaps.rst, configuration/packages/configuring-planner-server.rst, configuration/packages/configuring-recovery-server.rst
Signed-off-by: Sarthak Mittal <sarthakmittal2608@gmail.com>
Adds small notes for server plugin namespace list parameters to provide info about the existence and usage of the `plugin` parameter for each plugin namespace.
=> Add info for 'plugin' parameter for plugin namespaces

configuration/packages/configuring-costmaps.rst
Related to https://github.com/ros-planning/navigation2/issues/1874
=> Added clarification on footprint parameter syntax

configuration/packages/bt-plugins/actions/NavigateToPose.rst, migration/Foxy.rst, migration/index.rst
Related to https://github.com/ros-planning/navigation2/pull/1880.
=> Update NavigateToPose BT-node modification (Add Foxy.rst)

build_instructions/index.rst
Fix #39 
Signed-off-by: Miguel Company <MiguelCompany@eprosima.com>
=> Add rosdep step to manual build instructions

getting_started/index.rst
The added note should help new users or ROS 2 Dashing users avoid issues with
the "Getting Started" launch file, and also explain preference for Eloquent
and later.
ros-planning/navigation2#1607
ros-planning/navigation2#1663
ros-planning/navigation.ros.org#9
ros-planning/navigation.ros.org#36
=> Clarify "Getting Started" launch file change

configuration/packages/configuring-amcl.rst, configuration/packages/costmap-plugins/static.rst
For PR https://github.com/ros-planning/navigation2/pull/1910
=> Added map_topic documentation for amcl and static costmap layer

configuration/packages/configuring-costmaps.rst, configuration/packages/costmap-plugins/range.rst, migration/Eloquent.rst, plugins/index.rst
Connected to https://github.com/ros-planning/navigation2/pull/1888
=> Added range sensor costmap layer to documentation

2020summerOfCode/projects/grid_maps.rst, 2020summerOfCode/projects/testing.rst, README.md, build_instructions/build_docs/build_troubleshooting_guide.rst, build_instructions/index.rst, conf.py, configuration/packages/bt-plugins/actions/BackUp.rst, configuration/packages/bt-plugins/actions/ComputePathToPose.rst, configuration/packages/bt-plugins/actions/NavigateToPose.rst, configuration/packages/bt-plugins/actions/Spin.rst, configuration/packages/bt-plugins/actions/Wait.rst, configuration/packages/configuring-amcl.rst, configuration/packages/configuring-bt-navigator.rst, configuration/packages/configuring-bt-xml.rst, configuration/packages/configuring-controller-server.rst, configuration/packages/configuring-costmaps.rst, configuration/packages/configuring-lifecycle.rst, configuration/packages/configuring-map-server.rst, configuration/packages/configuring-navfn.rst, configuration/packages/configuring-planner-server.rst, configuration/packages/configuring-recovery-server.rst, configuration/packages/configuring-waypoint-follower.rst, migration/Eloquent.rst, plugins/index.rst, substitutions.txt, tutorials/docs/navigation2_on_real_turtlebot3.rst
Open questions: 
* Is Ros2 already on Main? (first 2 commits) - but only text
* ClearCostmap has some Master references that must be changed before docs change (master_grid)
+ adding dependency instructions for this README
+ small fix displaying ``--no-ros2`` correctly
Did build successfully on my machine.
=> Switch Master references to Main as master-branch of nav2 is deleted

plugins/index.rst
Signed-off-by: jediofgever <fetulahatas1@gmail.com>
In Navigation plugin [page](https://navigation.ros.org/plugins/index.html),   
waypoint task executor table had indent error as below; ,
the commit intents to fix that
=> way point task executor; fix unintended table in Navigation plugins page

configuration/packages/configuring-bt-navigator.rst, migration/Foxy.rst
In alignment with https://github.com/ros-planning/navigation2/pull/1958
=> Just groot migration and params

configuration/packages/configuring-controller-server.rst, configuration/packages/configuring-costmaps.rst, configuration/packages/configuring-map-server.rst, configuration/packages/costmap-plugins/keepout_filter.rst, configuration/packages/costmap-plugins/speed_filter.rst, migration/Foxy.rst, plugins/index.rst
This is related to https://github.com/ros-planning/navigation2/pull/2074 documentation update.
=> Update documentation with SpeedFilter

configuration/packages/configuring-costmaps.rst, configuration/packages/costmap-plugins/obstacle.rst, configuration/packages/costmap-plugins/voxel.rst, migration/Foxy.rst
* Documenting the `raytrace_min_range` and `raytrace_max_range` params introduced in this [pull request](https://github.com/ros-planning/navigation2/pull/2126).
=> Documentation changes for ray tracing param changes

setup_guides/transformation/setup_transforms.rst
This PR fixes inconsistencies in TF frame names in the "Setting Up Transformations" guide. The frame name for the laser appears as `base_laser` in all figures, however, it is referred to as `laser_link` in many places within the document which can confuse readers. This PR changes all instances of `laser_link` to `base_laser` in this document.
=> Update all instances of `laser_link` to `base_laser` for consistency

configuration/packages/configuring-map-server.rst, configuration/packages/costmap-plugins/speed_filter.rst
This complements https://github.com/ros-planning/navigation2/pull/2149 work.
=> Enable absolute values for speed_filter

configuration/packages/bt-plugins/actions/PlannerSelector.rst, configuration/packages/configuring-bt-xml.rst, migration/Foxy.rst, plugins/index.rst
Simple documentation to include the planner_selector on the migration guide.
=> planner_selector in migration guide

migration/Foxy.rst
Added the details on where PointCloud msg Publishers and data is changed to use PointCloud2 msg in Fory to Galactic migration.
=> Changed PointCloud msg publishers to PointCloud2 

configuration/packages/configuring-controller-server.rst, migration/Foxy.rst
For https://github.com/ros-planning/navigation2/pull/2264
=> [nav2_controller] Add failure_tolerance param

configuration/packages/configuring-bt-navigator.rst
As per https://github.com/ros-planning/navigation2/pull/2320
=> Add new BT navigator params

plugin_tutorials/docs/writing_new_costmap2d_plugin.rst, plugin_tutorials/docs/writing_new_nav2planner_plugin.rst, tutorials/docs/navigation2_with_stvl.rst
Plugin server updates happened between `Eloquent` and `Foxy`, not between `Foxy` and `Galactic` as originally  written. 
For quick check of correctness: `foxy-devel` branch of Nav2 uses `plugin` and not `plugin_name`/`plugin_type`, https://github.com/ros-planning/navigation2/blob/2e18dd1cae31807f68746eb1a2c702526a34f4cc/nav2_bringup/bringup/params/nav2_params.yaml#L170
See full thread here: https://navigation2.slack.com/archives/C012L20NQLV/p1622570382026000
=> Changing distros for pluginlib syntax change

build_instructions/index.rst
As per https://github.com/ros-planning/navigation2/issues/2388 Docker instructions on the documentation need to change. 
It is now recommended to install from apt, unless for development purposes.
=> updating docker build instructions and guidance

build_instructions/index.rst, concepts/index.rst, setup_guides/transformation/setup_transforms.rst, setup_guides/urdf/setup_urdf.rst, substitutions.txt, tutorials/docs/get_backtrace.rst
docs.ros.org has replaced index.ros.org/doc/ros2
I used `/rolling/` for the links because then they won't need to be updated.
Signed-off-by: Christophe Bedard <bedard.christophe@gmail.com>
=> Update links to ROS 2 docs

configuration/packages/configuring-amcl.rst, migration/Galactic.rst
I have added a sample xml snippet to the AMCL configuration file and changed the robot_model_type.
If needed I can include a more detailed step by step procedure about how to create a plugin for a custom motion model,may be not in the configuration file but as a separate sample tutorial.
=> Updated AMCL configuration file,and galactic migration guide

migration/Galactic.rst
for https://github.com/ros-planning/navigation2/pull/2772
=> PR documentation

migration/Galactic.rst
Signed-off-by: zhenpeng ge <zhenpeng.ge@qq.com>
add docs for https://github.com/ros-planning/navigation2/pull/2750
=> add migration for dynamic composition

configuration/packages/bt-plugins/actions/CancelControl.rst, configuration/packages/configuring-bt-xml.rst, migration/Galactic.rst, plugins/index.rst
Related PR in the code base: https://github.com/ros-planning/navigation2/pull/2787
=> adding descriptions for cancelControl BT

configuration/packages/configuring-amcl.rst
The previous example didn't really translate to the yaml format that has to be filled in there.
=> Fixed example for AMCL initial pose settings

commander_api/index.rst
- Related PR: https://github.com/ros-planning/navigation2/pull/2789
=> Added description for Commander API - followPath and example_follow_path.py 

commander_api/index.rst, migration/Galactic.rst
Follow up to https://github.com/ros-planning/navigation.ros.org/pull/268 and https://github.com/ros-planning/navigation2/pull/2792
=> Add recoveries simple commander

configuration/packages/trajectory_critics/prefer_forward.rst
There are 2 "scale" descriptions in this page, and it seems like an extra content.
=> Remove an extra parameter description in PreferForwardCritic page.

configuration/packages/configuring-amcl.rst
Added note about breaking change in AMCL motion model selection parameter.
=> Clarification to `robot_model_type` for users of galactic and earlier

commander_api/index.rst
Docs for https://github.com/ros-planning/navigation2/pull/2834
=> Add docs for commander API

setup_guides/sensors/setup_sensors.rst
An error occurs while trying to execute the above line in Galactic version of ROS2
The following PR adds a note for changes required in the code while working with Galactic or newer version of ROS2. The reference can be seen in Tf2 tutorial (https://docs.ros.org/en/galactic/Tutorials/Tf2/Introduction-To-Tf2.html#tf2-tools) mentioned in ROS2 Galactic documentation.
=> Updated setup_sensors.rst file with a Note 

configuration/packages/configuring-thetastar.rst
The PR commit is in sync with the latest version of the ROS2. If ran with the unedited version of Theta Star Planner on Galactic Version of ROS2, it fails to recognize the parameters during the configuration stage of the planner and defaults to NavFn_Planner.
=> Updated the ros__parameters of the Theta star planner in config guide

configuration/packages/configuring-regulated-pp.rst, configuration/packages/dwb-params/controller.rst
Corresponding documentation updates for https://github.com/ros-planning/navigation2/pull/2812
=> Path segment pr

commander_api/index.rst
Documentation for `destroyNode()` function proposed here: https://github.com/ros-planning/navigation2/pull/2924
=> Add docs for basic_navigator.destroyNode()

migration/Galactic.rst
Related to https://github.com/ros-planning/navigation2/pull/2965
=> Added goal checker API change note in migration guide

migration/Galactic.rst
As per https://github.com/ros-planning/navigation2/pull/2976
=> Add migration guide for nav2_core API changes

.circleci/config.yml, README.md
works on 20.04 and 22.04 as well.. #319 
apt-get installation of sphinx installs sphinx 1.8.0.. 
The newer version of Breathe supports versions between 3.0.0 and 3.5.0. Therefore, adding a pip3 install targeting the supported versioning for sphinx.
=> upgrading breathe version

configuration/packages/configuring-thetastar.rst
In order to run theta star planner,the official guide lost one parma:
w_heuristic_cost: 1.0
=> Theta Star config lost one parma

getting_started/index.rst
[Fixes #3024](https://github.com/ros-planning/navigation2/issues/3024)
=> Add non headless start to example command

substitutions.txt
The page describing how to install ROS 2 was moved.
=> Update link to description on how to install ROS 2

tutorials/docs/camera_calibration.rst
Hmm, i see that the checkerboard was 200mm squares in the [original tutorial](http://wiki.ros.org/camera_calibration/Tutorials/MonocularCalibration)
I'm going to convert this PR to a draft for now..
=> Fix checker width from 200mm to 20mm

configuration/packages/configuring-regulated-pp.rst
https://github.com/ros-planning/navigation2/pull/3047
=> add approach_velocity_scaling_dist parameter

setup_guides/sensors/setup_sensors.rst
* For low compute, delays in startup makes processes start in the wrong order, resulting in malformed tf trees
* Resulting log messages direct towards solving different problems, but problems are only symptoms of this specific problem
* For beginners, prevent spending too much time guessing what the problem could be
* Logs Timed out waiting for transform , frame does not exist
* RViz Global costmap No map received
* Message filter discarding message because queue is full
=> Add note for delayed startups

commander_api/index.rst
update Costmap API documentation as the Pull Request of navigation2
* ros-planning/navigation2#3169
=> update Costmap API documentation

commander_api/index.rst
Documentation for adding assisted teleop to the nav2_simple_commander.
=> added docs for assisted teleop

configuration/packages/configuring-regulated-pp.rst
This PR add a new parameter that enable/disable RPP collision detection to the documentation page of RPP.
This parameter is originally added in navigation2 repository by this PR: https://github.com/ros-planning/navigation2/pull/3204
=> Add parameter use_collision_detection to configuring-regulated-pp.rst

configuration/packages/bt-plugins/actions/ComputePathThroughPoses.rst, migration/Humble.rst
Documentation updates for https://github.com/ros-planning/navigation2/pull/3248.
=> docs for compute path through poses updates

configuration/packages/bt-plugins/actions/FollowPath.rst, migration/Humble.rst
Documentation for [controller exceptions](https://github.com/ros-planning/navigation2/pull/3227).
=> follow path exceptions

configuration/packages/configuring-map-server.rst
Documentation for the changes made in the launch file referring to this pull request https://github.com/ros-planning/navigation2/pull/3174.
=> Update yaml filename parameter for for map_server

migration/Humble.rst
Including the changes made in the pull request https://github.com/ros-planning/navigation2/pull/3174 to the migration guide.
=> Include way to set Map yaml file path for mapserver node behavior to migration guide

configuration/packages/bt-plugins/actions/SmootherSelector.rst, configuration/packages/configuring-bt-xml.rst, migration/Humble.rst, plugins/index.rst
This PR is related to https://github.com/ros-planning/navigation2/pull/3283
=> Added documentation for SmootherSelector

migration/Humble.rst
Documentation migration guide updates for https://github.com/ros-planning/navigation2/pull/3320.
=> Publish layers

configuration/packages/configuring-constrained-smoother.rst
Documentation updates related to the https://github.com/ros-planning/navigation2/pull/3341
=> Increase default w_smooth to 2M for Constrained Smoother

configuration/packages/configuring-collision-monitor.rst
between source and base frame during the movement.
This is documentation coverage for https://github.com/ros-planning/navigation2/pull/3412 PR and https://github.com/ros-planning/navigation2/issues/3402 issue.
=> Option allowing to consider or ignore time shifts

plugin_tutorials/docs/writing_new_nav2planner_plugin.rst
- Fix indentation in planner_server parameters
- Fix plugin by adding quotes "nav2_straightline_planner/StraightLine" and "nav2_navfn_planner/NavfnPlanner" Currently the presented configuration has wrong indentation which causes these error messages:
```
[planner_server-3] [ERROR] [1678443929.379055702] [rcl]: Failed to parse global arguments
[planner_server-3] terminate called after throwing an instance of 'rclcpp::exceptions::RCLInvalidROSArgsError'
[planner_server-3]   what():  failed to initialize rcl: Couldn't parse params file: '--params-file /home/user/ros2_ws/install/path_planner_server/share/path_planner_server/config/planner_server.yaml'. Error: Cannot have a value before ros__parameters at line 12, at /tmp/binarydeb/ros-galactic-rcl-yaml-param-parser-3.1.3/src/parse.c:793, at …
```
=> Fix planner_server parameters config example

configuration/packages/configuring-collision-monitor.rst, migration/Humble.rst
Added documentation for the new `state_topic` parameter in Collision Monitor. Please let me know if I missed out anything important to update!
=> update documentation for publishing collision monitor state

configuration/packages/configuring-collision-monitor.rst, migration/Humble.rst, tutorials/docs/using_collision_monitor.rst
Related to the https://github.com/ros-planning/navigation2/pull/3513 `max_points` -> `min_points` parameter rename.
`max_points` parameter meant the maximum number of points where we are still not triggering the action, while `min_points` - is a number starting from the action to be initiated. In other words, `min_points = max_points + 1`. So, default parameter values were also updated.
=> Collision Monitor max_points to min_points rename

conf.py
We're rolling all the ros.org sites forward to the new GA4 analytics ID.
=> add ros.org new analytics tag

concepts/index.rst
The **Behavior Tree** section in the [**Navigation Concepts**](https://navigation.ros.org/concepts/index.html) contained following the typo
```diff
This is opposed to a finite state machine (FSM) which may 
-then  
have dozens 
-or 
+of 
states and hundreds of transitions.
```
=> fix: typo fix in BT section

getting_started/index.rst
* The necessary deps are now installed when you install nav2_bringup, or use rosdep
* Follow up to https://github.com/ros-planning/navigation2/pull/3556
=> Remove tb3 manual install

configuration/packages/configuring-collision-monitor.rst, migration/Humble.rst
This is related to https://github.com/ros-planning/navigation2/pull/3519 change
=> Add new limit polygon description

plugin_tutorials/docs/writing_new_nav2controller_plugin.rst
The fix of https://github.com/ros-planning/navigation.ros.org/issues/423 issue request contains updates to the latest Nav2 status for controller plugins.
This includes:
* Added `setSpeedLimit`, introduced in https://github.com/ros-planning/navigation2/commit/6a0c92cad7fb8bb1e3e8500742bc293cddbedc36 and https://github.com/ros-planning/navigation2/commit/992deb0ff740e60189234455ac8c372fcaf2759c
* Added goal checker to the `computeVelocityCommands()` signature (and one sentence description) after https://github.com/ros-planning/navigation2/commit/d8bd3c5ea8d196ad7f0bace1edaeaa8e55f06944
* Update `configure()` signature, changed after https://github.com/ros-planning/navigation2/commit/4d596b91dcad20e61e67b9261a8200fc546af6f3 commit
=> Fix new controller plugin tutorial to latest Nav2 state

tuning/index.rst
The parameter name for a parameter file has a typo.
It's actually `param*s*_file`.
https://github.com/ros-planning/navigation2/blob/1b5920cc253e33a14cd94c81cccf670d13ee13cf/nav2_bringup/launch/bringup_launch.py#L41
=> Fix parameter name for params_file

configuration/packages/costmap-plugins/obstacle.rst, configuration/packages/costmap-plugins/voxel.rst, migration/Iron.rst, migration/index.rst
The documentation for [#3612](https://github.com/ros-planning/navigation2/pull/3612)
=> Option for ObstacleLayer to not overwrite StaticLayer's unknown parts

configuration/packages/configuring-mppic.rst, migration/Iron.rst
https://github.com/ros-planning/navigation2/pull/3659
=> adding MPPI align params for alignment

migration/Iron.rst
Fix misprint in PR link (forgotten underscore after link). Related to #462
=> Fix misprint in PR link

configuration/packages/configuring-behavior-server.rst, configuration/packages/configuring-bt-navigator.rst, configuration/packages/configuring-controller-server.rst, configuration/packages/configuring-planner-server.rst, configuration/packages/configuring-smoother-server.rst, configuration/packages/configuring-waypoint-follower.rst, configuration/packages/smac/configuring-smac-hybrid.rst, migration/Iron.rst
docs updates for https://github.com/ros-planning/navigation2/pull/3787
=> Action result timeout

configuration/index.rst, configuration/packages/collision_monitor/configuring-collision-monitor-node.rst
Add "Collision Monitor – Software-Based Safety Module" work reference, presented on 6th ROS Developers Day conference in 2023
=> Add Collision Monitor work at ROS Developers Day

configuration/packages/collision_monitor/configuring-collision-detector-node.rst, configuration/packages/collision_monitor/configuring-collision-monitor-node.rst, migration/Iron.rst
For https://github.com/ros-planning/navigation2/pull/3825
=> Add docs for #3825

migration/Iron.rst
this a Migration Guide PR for [this](https://github.com/ros-planning/navigation2/pull/3871) changes
=> add PR #3871 description to Iron.rst

configuration/packages/configuring-costmaps.rst, migration/Iron.rst
Add new parameter and migration guide for PR #3866
=> Update docu for PR #3866

configuration/packages/collision_monitor/configuring-collision-detector-node.rst, configuration/packages/collision_monitor/configuring-collision-monitor-node.rst, migration/Iron.rst
https://github.com/ros-planning/navigation2/pull/3880
=> Docs for 3880

configuration/packages/bt-plugins/actions/RemovePassedGoals.rst, configuration/packages/bt-plugins/conditions/GoalReached.rst
Remove `global_frame` input port from the `GoalReached` and `RemovePassedGoals` behavior nodes. Related to https://github.com/ros-planning/navigation2/pull/3917.
=> Enable goals to be sent in other frames than the pre-configured global_frame (documentation)

development_guides/build_docs/index.rst
* Use the correct branch
* Don't pull in vcs sources for geometry2
* Handle slam_toolbox circular dependency in the background automatically
* Add note that binaries are not available for rolling. If this changes, then a new section can be added
* Be able to compile NAV2 on rolling following the instructions verbatim without errors
Use this dockerfile:
```
ARG ROS_DISTRO=rolling
FROM ros:${ROS_DISTRO}-ros-core
RUN apt-get update \
&& apt-get install -y \
ros-dev-tools \
wget
WORKDIR /root/ros2_ws 
RUN mkdir -p ~/ros2_ws/src
RUN git clone https://github.com/ros-planning/navigation2.git --branch main ./src/navigation2
RUN rosdep init
SHELL ["/bin/bash", "-c"]
RUN apt-get update \
&& rosdep update \
&& source /opt/ros/${ROS_DISTRO}/setup.bash \
&& rosdep install -y -r --ignore-src …
```
=> Fix installation for rolling

configuration/index.rst, configuration/packages/configuring-graceful-motion-controller.rst, migration/Iron.rst, plugins/index.rst
Documentation for [#4021](https://github.com/ros-planning/navigation2/pull/4021)
=> Documentation for Graceful Motion

configuration/packages/configuring-controller-server.rst
This PR complements #302, reflecting https://github.com/ros-planning/navigation2/pull/2269 in the documents.
This PR consists of ...
- modification of the type of `goal_checker_plugins` parameter and its example
- description of how to handle `goal_checker_id` field in `FollowPath` actions with the parameter
=> Improve description of goal_checker_plugins

configuration/packages/configuring-thetastar.rst, configuration/packages/smac/configuring-smac-2d.rst, configuration/packages/smac/configuring-smac-hybrid.rst, configuration/packages/smac/configuring-smac-lattice.rst, migration/Iron.rst
https://github.com/ros-planning/navigation2/pull/4148
=> Updates for the cancel checker (PR  #4148)

configuration/packages/configuring-bt-navigator.rst, migration/Iron.rst
- Update migration and BtNavigator configuration guides with information regarding https://github.com/ros-planning/navigation2/pull/4209. 
- Fixed small typo in migration guide.
=> Add docs for new BtActionServer/Navigator parameter

configuration/packages/collision_monitor/configuring-collision-monitor-node.rst, migration/Iron.rst
Update collision_monitor configuration guide and migration guide with description of new parameter `<polygon_name>.polygon_subscribe_transient_local` introduced by PR https://github.com/ros-planning/navigation2/pull/4207.
=> Collision monitor transient local sub new param

configuration/packages/configuring-behavior-server.rst, configuration/packages/configuring-bt-navigator.rst, configuration/packages/configuring-navfn.rst, configuration/packages/configuring-planner-server.rst, configuration/packages/configuring-thetastar.rst, configuration/packages/smac/configuring-smac-2d.rst, configuration/packages/smac/configuring-smac-hybrid.rst, configuration/packages/smac/configuring-smac-lattice.rst, migration/Iron.rst, plugin_tutorials/docs/writing_new_behavior_plugin.rst, plugin_tutorials/docs/writing_new_costmap2d_plugin.rst, plugin_tutorials/docs/writing_new_nav2controller_plugin.rst, plugin_tutorials/docs/writing_new_nav2planner_plugin.rst, plugin_tutorials/docs/writing_new_navigator_plugin.rst, setup_guides/algorithm/select_algorithm.rst
Modify the website base on https://github.com/ros-planning/navigation2/pull/4220
=> Refactor the plugin names for bt_navigator to use double colons

behavior_trees/overview/detailed_behavior_tree_walkthrough.rst
Replaced
tree will execute *unless* the battery becomes low (and then ***entire*** a different subtree for docking to recharge).
tree will execute *unless* the battery becomes low (and then ***enter*** a different subtree for docking to recharge).
=> Typo on detailed_behavior_tree_walkthrough.rst

configuration/packages/collision_monitor/configuring-collision-monitor-node.rst, migration/Iron.rst
Update collision_monitor configuration guide and migration guide with description of new parameter `<polygon_name>.radius_sub_topic` introduced by PR https://github.com/ros-planning/navigation2/pull/4226.
=> Collision monitor circle radius sub new param

configuration/packages/configuring-mppic.rst
This PR adds documentation for the main [nav2_mppi_controller PR](https://github.com/ros-planning/navigation2/pull/4256)
=> Add docs for Velocity Deadband Critic

setup_guides/urdf/setup_urdf.rst
Improved pull request for #548.
Launching this code with the option 'gui:=False' gives errors in RVIZ. The correct way of using parameters in the code is 'parameters' argument. The argument 'arguments' is for command line arguments.
=> Replace incorrect 'arguments' with 'parameters' 2

configuration/packages/costmap-plugins/static.rst, migration/Iron.rst
Docs for https://github.com/ros-planning/navigation2/pull/4282
=> Add docs for static layer param footprint_clearing_enabled

configuration/packages/collision_monitor/configuring-collision-detector-node.rst, configuration/packages/collision_monitor/configuring-collision-monitor-node.rst, configuration/packages/configuring-amcl.rst, configuration/packages/configuring-behavior-server.rst, configuration/packages/configuring-bt-navigator.rst, configuration/packages/configuring-controller-server.rst, configuration/packages/configuring-map-server.rst, configuration/packages/configuring-planner-server.rst, configuration/packages/configuring-smoother-server.rst, configuration/packages/configuring-velocity-smoother.rst, configuration/packages/configuring-waypoint-follower.rst, migration/Iron.rst
For https://github.com/ros-navigation/navigation2/pull/4342
=> Docs for PR4342

configuration/packages/configuring-mppic.rst, migration/Iron.rst
docs update for new acceleration constraint parameters in the MPPI controller.
=> Docs update for the PR #4352 Add acceleration constraints in the MPPI controller

concepts/index.rst
Looking at [a behavior tree example from nav2_bt_navigator](https://github.com/ros-navigation/navigation2/blob/main/nav2_bt_navigator/behavior_trees/navigate_to_pose_w_replanning_and_recovery.xml#L7) I see the version was changed 4 months ago but the doc wasn't updated.
=> update behaviour tree version

configuration/packages/configuring-regulated-pp.rst, migration/Iron.rst
Merge after [ros-navigation/navigation2/pull/4441](https://github.com/ros-navigation/navigation2/pull/4441) is merged
=> Documentation of RPP use_cancel_deceleration parameter

migration/Jazzy.rst
Updates https://github.com/ros-navigation/navigation2/pull/4458
=> Added new docking panel to Jazzy migration

migration/Humble.rst
Just some little typos in migration guideline are fixed for redirection of PRs
=> Update Humble.rst for typos in url

migration/Jazzy.rst
Merge after [PR](https://github.com/ros-navigation/navigation2/pull/4546) is merged
=> Documentation for rviz costmap costcell's cost tool

configuration/index.rst, configuration/packages/configuring-loopback-sim.rst, migration/Jazzy.rst
https://github.com/ros-navigation/navigation2/pull/4614
=> Adding docs for loopback sim

configuration/packages/configuring-controller-server.rst, migration/Jazzy.rst
https://github.com/ros-navigation/navigation2/pull/4675
=> doc(controller-server): publish_zero_velocity parameter

requirements.txt
The CSS layout is currently missing. Updating packages version solved the layout issue.
=> CSS layout not working properly issue. Made changes to packages version.

plugins/index.rst
[Via this comment](https://github.com/ros-navigation/docs.nav2.org/pull/590/files#r1821882224)
=> Roll back merge error

plugins/index.rst
Fix typo in link target for the "Reinitialize Global Localization Service" BT node
=> fix typo in BT node plugin list

configuration/packages/configuring-costmaps.rst, configuration/packages/costmap-plugins/obstacle.rst, configuration/packages/costmap-plugins/range.rst, configuration/packages/costmap-plugins/static.rst, configuration/packages/costmap-plugins/voxel.rst, migration/Jazzy.rst, tuning/index.rst
Add migration for PR https://github.com/ros-navigation/navigation2/pull/4715
=> Add note on multirobot refactor to migration guide

migration/Jazzy.rst
The actual name everywhere else in the documentation is `enable_stamped_cmd_vel` and that is what works on current rolling as well.
=> fix parameter name to enable_stamped_cmd_vel

.gitignore, plugin_tutorials/docs/writing_new_behavior_plugin.rst, plugin_tutorials/docs/writing_new_nav2controller_plugin.rst, plugin_tutorials/docs/writing_new_nav2planner_plugin.rst, plugin_tutorials/docs/writing_new_navigator_plugin.rst
https://github.com/ros-navigation/navigation2/issues/4815
=> Add more details for class name

tutorials/docs/docker_dev.rst
This pull request includes a small change to the `tutorials/docs/docker_dev.rst` file. The change corrects a redundant command in the bash code block.
=> fix typo in bash code block 

migration/Jazzy.rst
Documentation changes for https://github.com/ros-navigation/navigation2/pull/4811.
Should I add an example of what was the problem with the original parsing namely that something like the following didn't work as expected:
```python
IncludeLaunchDescription(
PythonLaunchDescriptionSource(
os.path.join(get_package_share_directory('nav2_bringup'), "launch", "cloned_multi_tb3_simulation_launch.py")
),
launch_arguments={"robots": "robot1={x: 0.5, y: 0.5, yaw: 1.5707}"}.items(),
)
```
or is this not relevant for the documentation?
=> Add note about multi-robot launch file changes

configuration/packages/configuring-behavior-server.rst, migration/Jazzy.rst
New docs for params introduced by PR https://github.com/ros-navigation/navigation2/pull/4810.
=> Documentation for acceleration limits in DriveOnHeading and BackUp behaviors

tutorials/docs/docker_dev.rst
Example used non-existing NAV2_BRANCH variable instead of ROS_DISTRO
=> Fix ROS-version argument in docker_dev.rst example

configuration/packages/bt-plugins/conditions/IsPathValid.rst
https://github.com/ros-navigation/navigation2/pull/4873
=> Add new parameter description in ispathvalid

configuration/packages/configuring-rotation-shim-controller.rst, migration/Jazzy.rst
Add docs for https://github.com/ros-navigation/navigation2/pull/4880
=> Rotation Shim closed_loop param

configuration/packages/bt-plugins/conditions/InitialPoseReceived.rst, configuration/packages/bt-plugins/conditions/IsBatteryCharging.rst, configuration/packages/bt-plugins/conditions/IsBatteryLow.rst, configuration/packages/bt-plugins/conditions/PathExpiringTimer.rst
Some nodes are missing the input port table, I have added it in this PR
=> Add table for input ports in condition nodes

configuration/packages/bt-plugins/conditions/AreErrorCodesPresent.rst
In behavior trees, lists provided as parameters must be semicolon-separated, and not comma-separated. Source: https://github.com/BehaviorTree/BehaviorTree.CPP/blob/master/src/basic_types.cpp#L217
=> Fix example syntax for the AreErrorCodesPresent BT node

configuration/packages/bt-plugins/actions/ComputePathThroughPoses.rst, configuration/packages/bt-plugins/actions/NavigateThroughPoses.rst, configuration/packages/bt-plugins/actions/RemoveInCollisionGoals.rst, configuration/packages/bt-plugins/actions/RemovePassedGoals.rst, configuration/packages/bt-plugins/conditions/GlobalUpdatedGoal.rst, configuration/packages/bt-plugins/conditions/GoalUpdated.rst, configuration/packages/bt-plugins/decorators/GoalUpdatedController.rst, configuration/packages/bt-plugins/decorators/GoalUpdater.rst, configuration/packages/bt-plugins/decorators/SpeedController.rst, migration/Jazzy.rst
This modifies the documentation to handle the migration of `geometry_msgs/PoseStamped` to `nav_msgs/Goals` in https://github.com/ros-navigation/navigation2/pull/4980.
The following changes have been verified using `make html` and opening the `_build/html/index.html` file on a browser window.
=> Migrate `geometry_msgs/PoseStampedArray` to `nav_msgs/Goals`

migration/Jazzy.rst
This modifies the documentation to handle the deprecation of `ParseMultiRobotPose` in https://github.com/ros-navigation/navigation2/pull/5000.
The following changes have been verified using `make html` and opening the `_build/html/index.html` file on a browser window.
=> Migrate multi robot launch to use updated robot string syntax.

configuration/packages/configuring-mppic.rst, migration/Jazzy.rst
https://github.com/ros-navigation/navigation2/pull/4996
=> Add near collision cost

configuration/packages/configuring-rotation-shim-controller.rst, migration/Jazzy.rst
See https://github.com/ros-navigation/navigation2/pull/5034
=> Add Rotation Shim Controller Use Path Orientations

configuration/packages/configuring-amcl.rst, configuration/packages/configuring-bt-navigator.rst, configuration/packages/configuring-costmaps.rst, configuration/packages/configuring-docking-server.rst, configuration/packages/configuring-lifecycle.rst, configuration/packages/configuring-map-server.rst, configuration/packages/configuring-planner-server.rst, configuration/packages/configuring-waypoint-follower.rst, migration/Jazzy.rst
https://github.com/ros-navigation/navigation2/pull/4955
=> Add service introspection in configuration guide

setup_guides/sensors/setup_sensors_gz.rst
While working with Gazebo Harmonic, I encountered an issue where the "ray" tag no longer seems to function as expected. After some troubleshooting, I found out by looking at  the TurtleBot3 project that the documentation is currently outdated and replacing "ray" with "lidar" resolved the problem.
=> fix: deprecated tag `<ray>`, use `<lidar>` instead

configuration/packages/bt-plugins/actions/ComputePathToPose.rst
https://github.com/ros-navigation/navigation2/pull/4925
=> docs for PR 4925

tutorials/docs/adding_a_nav2_task_server.rst
Hi,
I just completed the tutorial and noticed a few spelling errors in the documentation. I've gone ahead and corrected them to improve clarity and consistency. The changes mainly involve minor typos, such as the incorrect usage of "errors codes" instead of "error codes".
Let me know if you need any further adjustments or clarifications.
Thanks!
=> Fix spelling and grammar issues in Task Server documentation

.gitignore, README.md
* Add `venv/` folder to the `.gitignore` file to ignore virtual Python files.
* Update documentation to enable installation of the Python dependencies in a virtual environment.
=> Add venv support

concepts/index.rst
Changed from Four to Five in representing action servers.
Note:
While I was reading through the documentation I found this blunder. I don't know, if that was on purpose or really a blunder, if it is you can merge this or close this request.
=> Minor changes in Planner, Controller, Smoother, Route and Behaviour Servers in Navigation Concepts

setup_guides/transformation/setup_transforms.rst
For broadcasting static transform the command arguments are old-style which are deprecated so changing it to new-style.
=> Changing from old-style arguments to new-style arguments in Setting Up Transforms

setup_guides/odom/setup_odom_gz_classic.rst
The current links in setting up odometry for gazebo classic is removed and ported to different domain.
I also saw two things while reading the documentation:
1. In **First Time Robot Setup Guide** page, on **Transforms in Navigation 2** topic in **Setting Up Transformations** the abbreviation for URDF is given as Universal Robot Descriptor File, I think it can also be called that way😄.
2. In the same page, on **Writing the URDF** topic in **Setting Up the URDF** there is a line  **"For code block block given below"**, when I read that first time it was confusing, are you're mentioning the code-block directive there or it's an typo.
Sorry for the long paragraphs 😄 trying to help you guys back.
=> Changed the links for Gazebo classic.

configuration/packages/configuring-smoother-server.rst, configuration/packages/configuring-thetastar.rst
As noted in https://github.com/ros-navigation/navigation2/blob/ee2d7789e70a968e6194af08030b425f3c591084/nav2_theta_star_planner/README.md?plain=1#L77
heuristic cost is an internal setting that is not user changeable, I don't think it is necessary to put it in the example
=> Update theta star planner and smoother server

configuration/packages/configuring-bt-navigator.rst, configuration/packages/configuring-constrained-smoother.rst, configuration/packages/configuring-controller-server.rst, configuration/packages/configuring-costmaps.rst, configuration/packages/configuring-dwb-controller.rst, configuration/packages/configuring-graceful-motion-controller.rst, configuration/packages/configuring-regulated-pp.rst, configuration/packages/configuring-rotation-shim-controller.rst, configuration/packages/configuring-thetastar.rst, configuration/packages/smac/configuring-smac-2d.rst, configuration/packages/smac/configuring-smac-hybrid.rst, configuration/packages/smac/configuring-smac-lattice.rst, plugin_tutorials/docs/writing_new_behavior_plugin.rst, plugin_tutorials/docs/writing_new_bt_plugin.rst, plugin_tutorials/docs/writing_new_costmap2d_plugin.rst, plugin_tutorials/docs/writing_new_nav2planner_plugin.rst, plugin_tutorials/docs/writing_new_navigator_plugin.rst, setup_guides/footprint/setup_footprint.rst, setup_guides/sensors/mapping_localization.rst, tutorials/docs/navigation2_with_keepout_filter.rst, tutorials/docs/navigation2_with_speed_filter.rst, tutorials/docs/navigation2_with_stvl.rst, tutorials/docs/using_collision_monitor.rst, tutorials/docs/using_shim_controller.rst
I think with https://github.com/ros-navigation/navigation2/pull/3131, it is safe to remove all use_sim_time in the docs
=> Remove use_sim_time from yaml

configuration/packages/costmap-plugins/obstacle.rst
min_obstacle_height here https://github.com/ros-navigation/navigation2/blob/27dab69edfd05f8e2c6d77d232c008a92fd5b5f5/nav2_costmap_2d/plugins/obstacle_layer.cpp#L98 is not documented 
I am also curious why does this parameter does not exist in voxel layer
https://github.com/ros-navigation/navigation2/blob/27dab69edfd05f8e2c6d77d232c008a92fd5b5f5/nav2_costmap_2d/plugins/voxel_layer.cpp#L197
=> Add missing min_obstacle_height in obstacle layer

configuration/packages/smac/configuring-smac-2d.rst
I think do_refinement and refinement_num is missing in smacplanner2d(?)
=> Add missing smac planner2d smoother parameters

configuration/packages/configuring-behavior-server.rst, configuration/packages/configuring-savitzky-golay-smoother.rst, configuration/packages/configuring-simple-smoother.rst, configuration/packages/configuring-smoother-server.rst, plugin_tutorials/docs/writing_new_behavior_plugin.rst, tutorials/docs/adding_smoother.rst
some of the configs are still using transform_timeout, this PR replaced it with transform_tolerance to match the current version
=> Rename transform_timeout as transform_tolerance in configs

.github/dependabot.yml
* Removed `pip` version checking for `dependabot`.
=> Remove pip dependabot configuration.

configuration/packages/configuring-bt-navigator.rst, migration/Kilted.rst
Update migration guide for https://github.com/ros-navigation/navigation2/pull/5466
=> Update moved BT Navigator params

configuration/packages/configuring-savitzky-golay-smoother.rst, migration/Kilted.rst
https://github.com/ros-navigation/navigation2/pull/5489
=> Add custom window size and poly order for SG filter

configuration/packages/configuring-mppic.rst
https://github.com/ros-navigation/navigation2/pull/5485
=> docs for publish_critics_stats

.github/PULL_REQUEST_TEMPLATE.md
---
| Info | Please fill out this column |
| ------ | ----------- |
| Ticket(s) this addresses   | N/A |
| Does this PR contain AI-generated software? | No |
---
* Added a PR template with a table linking the repositories' tickets, along with [ros-navigation/navigation2](https://github.com/ros-navigation/navigation2) tickets for ease of contribution.
* I have used the embedded template as a demonstration for this contribution for ease of review.
=> Added pull request template to facilitate standardized contributions.

configuration/packages/bt-plugins/actions/ToggleCollisionMonitor.rst, configuration/packages/collision_monitor/configuring-collision-monitor-node.rst, tutorials/docs/using_collision_monitor.rst
---
| Info | Please fill out this column |
| ------ | ----------- |
| Ticket(s) this addresses   | https://github.com/ros-navigation/navigation2/pull/5554 |
| Does this PR contain AI-generated software? | No |
---
* Added description for the `enabled` parameter to configuration guide.
* Updated template parameter files in both configuration guide and tutorial with this new parameter.
=> Update collision monitor documentation with the new enabled parameter

configuration/packages/bt-plugins/actions/ToggleCollisionMonitor.rst, migration/Kilted.rst
Fix default service name for toggle collision monitor.
---
| Info | Please fill out this column |
| ------ | ----------- |
| Ticket(s) this addresses   | #780 |
| Does this PR contain AI-generated software? | No |
---
Change the default service name :=)
=> Fix default service name for toggle collision monitor
